name = "cobbleverse"
author = "jesus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5ab112346be427d60e35500be66d75e358459643438a6ac9db49347172f66d1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
