name = "cobbleverse"
author = "jesus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26a5f6ba4c663e604856801e6699afa9e14f845ff06a8593e00a3b50b018a24e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
