name = "cobbleverse"
author = "jesus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59a8e3f84499555533e27e81f13308390bdc055f399c495799086b8146a40286"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
