name = "cobbleverse"
author = "jesus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad612e498ddd2570a9703e80f3c93626f04f596ce23fbd3ac34a3d0224c54a48"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
