name = "cobbleverse"
author = "jesus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2e9133fc169f5b32f921261bf13f205a8e9a7e237d742f741ddf77679d6de60"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
