name = "cobbleverse"
author = "jesus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3d48b07619a7a42e488a481744679be6b971b9f7dc64a024d09c5ac72ad77e5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
